# core/reporters/html_reporter.py
from __future__ import annotations
import html
from dataclasses import is_dataclass, asdict
from typing import Any, List

def _obj_to_dict(obj: Any) -> Any:
    if is_dataclass(obj):
        return asdict(obj)
    return obj

def _escape(s: Any) -> str:
    return html.escape("" if s is None else str(s))

def _severity_color(sev: str) -> str:
    sev = (sev or "").upper()
    if sev == "HIGH":
        return "#b71c1c"
    if sev == "MEDIUM":
        return "#e65100"
    return "#01579b"  # INFO/LOW

def write_html_report(result: Any, path: str) -> str:
    """
    Minimal but clean HTML report. Expects `result` to have keys/fields:
      - target, crawled_pages, discovered_forms, started_at, finished_at
      - findings: List[ {severity, category, url, param, evidence} ]
      - pages: List[str] (optional)
    """
    r = _obj_to_dict(result)
    target = r.get("target", "")
    pages_n = r.get("crawled_pages", 0)
    forms_n = r.get("discovered_forms", 0)
    dur = None
    try:
        st = float(r.get("started_at") or 0.0)
        fn = float(r.get("finished_at") or 0.0)
        if fn > st:
            dur = f"{fn - st:.1f}s"
    except Exception:
        pass

    findings: List[dict] = r.get("findings", []) or []
    # sort by severity HIGH -> MEDIUM -> INFO
    sev_order = {"HIGH": 0, "MEDIUM": 1, "INFO": 2, "LOW": 2}
    findings.sort(key=lambda f: sev_order.get(str(f.get("severity")).upper(), 3))

    rows = []
    for f in findings:
        sev = _escape(f.get("severity"))
        cat = _escape(f.get("category"))
        url = _escape(f.get("url"))
        prm = _escape(f.get("param"))
        evd = _escape(f.get("evidence"))
        color = _severity_color(sev)
        rows.append(
            f"<tr>"
            f"<td style='color:{color};font-weight:600'>{sev}</td>"
            f"<td>{cat}</td>"
            f"<td style='word-break:break-all'>{url}</td>"
            f"<td>{prm}</td>"
            f"<td style='white-space:pre-wrap'>{evd}</td>"
            f"</tr>"
        )

    top_pages = r.get("pages") or []

    html_doc = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>TSA Web Tester Report</title>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<style>
 body {{ font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 24px; }}
 .card {{ background:#fff; border:1px solid #e5e7eb; border-radius:12px; box-shadow:0 1px 2px rgba(0,0,0,.04); padding:20px; margin-bottom:20px; }}
 h1 {{ margin:0 0 12px; font-size:22px; }}
 h2 {{ margin:0 0 12px; font-size:18px; }}
 table {{ width:100%; border-collapse:collapse; }}
 th, td {{ padding:10px; border-bottom:1px solid #eee; vertical-align:top; }}
 th {{ text-align:left; background:#fafafa; font-weight:600; }}
 .pill {{ display:inline-block; padding:3px 8px; border-radius:999px; background:#eef2ff; color:#3730a3; font-size:12px; margin-left:6px; }}
 .muted {{ color:#6b7280; }}
 ul {{ margin:8px 0 0 18px; }}
 code {{ background:#f3f4f6; padding:2px 4px; border-radius:6px; }}
</style>
</head>
<body>

<div class="card">
  <h1>TSA Web Tester Report</h1>
  <div class="muted">
    <b>Target:</b> {html.escape(str(target))}
    <span class="pill">Pages: {pages_n}</span>
    <span class="pill">Forms: {forms_n}</span>
    {"<span class='pill'>Duration: "+dur+"</span>" if dur else ""}
  </div>
</div>

<div class="card">
  <h2>Findings (sorted by severity)</h2>
  <table>
    <thead>
      <tr>
        <th>Severity</th><th>Category</th><th>URL</th><th>Param</th><th>Evidence</th>
      </tr>
    </thead>
    <tbody>
      {''.join(rows) if rows else "<tr><td colspan='5' class='muted'>No findings.</td></tr>"}
    </tbody>
  </table>
</div>

<div class="card">
  <h2>Top Crawled Pages</h2>
  {"<ul>" + "".join(f"<li>{html.escape(p)}</li>" for p in top_pages[:50]) + "</ul>" if top_pages else "<div class='muted'>No pages captured.</div>"}
</div>

<div class="muted">Generated by TSA Web Tester</div>
</body>
</html>"""
    with open(path, "w", encoding="utf-8") as f:
        f.write(html_doc)
    return path
